# Functions for reading and plotting Zephyr biopatch data -----
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

require(dplyr)
require(tidyr)
require(tibble)
require(readr)
require(lubridate)
require(ggplot2)
require(scales)

### Reader functions

#Reads *_Accel.csv files originally generated by the Zephyr biopatch.
#This function expects these data contain an extra "VectorMagnitude"
#column calculated from the three axes of motion.
read.BioPatch_accelerometer_data <- function(filename,
                                             subjectID,
                                             time_zone=default_timezone,
                                             #Device num used to differentiate multiple BioPatches
                                             #used for the same subject.
                                             device_num = NA_character_) {
    #Read raw data file
    BioPatch.raw_data =
        readr::read_csv(filename,
                        col_types = 
                            readr::cols(
                                Time = col_character(),
                                Vertical = col_double(),
                                Lateral = col_double(),
                                Sagittal = col_double(),
                                VectorMagnitude = col_double()
                            )) %>% 
        dplyr::mutate(SubjectID = subjectID,
                      BioPatch_Num = device_num,
                      Source = "ZephyrBioPatch")
    
    #Convert DateTime to POSIXct format
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        mutate(DateTime = dmy_hms(Time, tz=time_zone)) %>% 
        filter(!is.na(DateTime)) %>% 
        select(-Time)
    
    #Reduce data to standardized format
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        tidyr::gather(Measurement, Value, Vertical, Lateral, Sagittal, VectorMagnitude) %>% 
        dplyr::mutate(Misc = paste0("BioPatch_", BioPatch_Num)) %>% 
        dplyr::select(SubjectID, DateTime, Source, Measurement, Value, Misc)
    
    return(BioPatch.raw_data)
}


#Reads *_Breathing.csv files originally generated by the Zephyr biopatch.
#These contain the BreathingWaveform.
read.BioPatch_breathing_data <- function(filename,
                                         subjectID,
                                         time_zone=default_timezone,
                                         #Device num used to differentiate multiple BioPatches
                                         #used for the same subject.
                                         device_num = NA_character_) {
    #Read raw data file
    BioPatch.raw_data =
        readr::read_csv(filename,
                        col_types = 
                            readr::cols(
                                Time = col_character(),
                                BreathingWaveform = col_integer()
                            )) %>% 
        dplyr::mutate(SubjectID = subjectID,
                      BioPatch_Num = device_num,
                      Source = "ZephyrBioPatch")
    
    #Convert DateTime to POSIXct format
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        mutate(DateTime = dmy_hms(Time, tz=time_zone)) %>% 
        filter(!is.na(DateTime)) %>% 
        select(-Time)
    
    #Reduce data to standardized format
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        tidyr::gather(Measurement, Value, BreathingWaveform) %>% 
        dplyr::mutate(Misc = paste0("BioPatch_", BioPatch_Num)) %>% 
        dplyr::select(SubjectID, DateTime, Source, Measurement, Value, Misc)
    
    return(BioPatch.raw_data)
}


#Read heart rate, breathing rate, posture, activity, peak acceleration, ECG
#amplitude, ECG noise, HR confidence, HRV (Heart Rate Variability), vertical
#minimum acceleration, vertical peak acceleration, lateral minimum acceleration,
#lateral peak acceleration, sagittal minimum acceleration, sagittal peak
#acceleration, estimated core temperature, skin temperature data from .CSV files
#generated by Zephyr BioPatch instrument/software.
read.BioPatch_data.everything <- function(filename,
                                          subjectID,
                                          time_zone=default_timezone,
                                          #Device num used to differentiate multiple BioPatches
                                          #used for the same subject.
                                          device_num = NA_character_) {
    #Read raw data file
    BioPatch.raw_data =
        readr::read_csv(filename,
                        col_types =
                            cols(
                                .default = col_double(),
                                Time = col_character(),
                                HR = col_integer(),
                                Posture = col_integer(),
                                BatteryLevel = col_integer(),
                                BRConfidence = col_integer(),
                                HRConfidence = col_integer(),
                                HRV = col_integer(),
                                SystemConfidence = col_integer(),
                                GSR = col_integer(),
                                ROGState = col_integer(),
                                ROGTime = col_integer(),
                                StatusInfo = col_integer(),
                                LinkQuality = col_integer(),
                                RSSI = col_integer(),
                                TxPower = col_integer(),
                                AuxADC1 = col_integer(),
                                AuxADC2 = col_integer(),
                                AuxADC3 = col_integer()
                            ))
    
    #Add additional columns
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        dplyr::mutate(SubjectID = subjectID,
                      BioPatch_Num = device_num,
                      Source = "ZephyrBioPatch")
    
    #Convert DateTime to POSIXct format
    BioPatch.raw_data = 
        BioPatch.raw_data %>% 
        dplyr::mutate(DateTime = lubridate::dmy_hms(Time, tz=time_zone)) %>% 
        dplyr::filter(!is.na(DateTime)) %>% 
        dplyr::select(-Time)
    
    #Re-order table
    BioPatch.raw_data =
        BioPatch.raw_data %>% 
        dplyr::mutate(Misc = paste0("BioPatch_", BioPatch_Num)) %>% 
        tidyr::gather(Measurement, Value, HR, BR, SkinTemp, Posture, Activity,
                      PeakAccel, BRAmplitude, BRNoise, BRConfidence, ECGAmplitude,
                      ECGNoise, HRConfidence, HRV, VerticalMin, VerticalPeak,
                      LateralMin, LateralPeak, SagittalMin, SagittalPeak, CoreTemp) %>% 
        dplyr::select(SubjectID, DateTime, Source, Measurement, Value, Misc)
    
    return(BioPatch.raw_data)
}


####Generic Plotting functions

#' Plot generic time series data
#'
#' Plot time series data given a table with a specific format. This particular
#' version of the function is designed to plot data spanning 1-3 days. The
#' x-axis labels and break points are optimized for data over this period.
#'
#' @param input_data data.frame containing tidyr-formatted time series data.It
#'   must have the following column names: DateTime, Value, Display_Group,
#'   Display_Facet.
#' @param y_axis_label String specifying display label for the y-axis
#' @param display_color_mapping Named vector mapping values in the Display_Group
#'   column of input_data to specific colors.
#' @param x_axis_range Two-element vector specifying the range for the x-axis.
#'   The vector elements should be POSIXct objects. If omitted, the range is
#'   derived from the DateTime column of input_data.
#' @param y_axis_range Two-element vector specifying the range of the y-axis. If
#'   omitted, the range is derived from the Value column of input_data.
#' @param shaded_regions data.frame with two columns, named start and end,
#'   defining the start and end times for shaded spans on the plot (e.g. periods
#'   of sleep or night in circadian data). Each row in this data.frame defines a
#'   different shaded region.
#' @param vertical_line_locations Vector of POSIXct objects listing the times on
#'   the x-axis at which to draw vertical lines on the plot.
#' @param time_zone String identifying the time zone of all POSIXct objects
#'   plotted in this graph (Default: "America/New_York").
#'
#' @return A ggplot object defining the time series graph.
#'   
plot_generic_time_series.multiple_days <- function(input_data,
                                                   y_axis_label,
                                                   display_color_mapping,
                                                   x_axis_range=NULL,
                                                   #x_scale="hours",
                                                   #TODO: Update function so user has full control over this parameter,
                                                   #      rather than keeping it hidden.
                                                   # param x_scale "hours" (default) or "days". Determines density of labels on
                                                   #   x-axis. "hours" will display ticks every 3 hours and is best suited for
                                                   #   plotting less than 1 week of data. "days" will display on tick every day
                                                   #   and is best for plotting up to a month of data.
                                                   y_axis_range=NULL,
                                                   shaded_regions=NULL,
                                                   vertical_line_locations=NULL,
                                                   time_zone=default_timezone) {
    
    #If no x-axis range specified, use range from input_data
    if(is.null(x_axis_range)) {
        x_axis_range =
            c(min(input_data$DateTime, na.rm = TRUE),
              max(input_data$DateTime, na.rm = TRUE))
    }
    
    #Determine scaling to use for x-axis
    x_scale = "hours"
    if(as.numeric(difftime(x_axis_range[2],
                           x_axis_range[1],
                           units = c("days"))) > 5) {
        x_scale = "days"
    }
    
    #If no y-axis range specified, use range from input_data
    if(is.null(y_axis_range)) {
        y_axis_range =
            c(min(input_data$Value, na.rm=TRUE),
              max(input_data$Value, na.rm=TRUE))
    }
    
    #Generate base plot for current data type
    figure_plot = 
        input_data %>% 
        ggplot(aes(x = DateTime, y = Value, group=Display_Group, color=Display_Group)) +
        geom_line()
    
    #Add shaded regions
    if(!is.null(shaded_regions)) {
        figure_plot =
            figure_plot +
            geom_rect(data = shaded_regions, inherit.aes = FALSE,
                      aes(ymin = -Inf, ymax = Inf,
                          xmin = start, xmax = end),
                      fill="black", alpha = 0.15)
    }
    
    #Add vertical lines
    if(!is.null(vertical_line_locations)) {
        figure_plot =
            figure_plot +
            geom_vline(xintercept = as.numeric(vertical_line_locations),
                       color="black")
    }
    
    #Add scale
    if ( x_scale == "days" ) {
        figure_plot =
            figure_plot +
            scale_x_datetime(name = element_blank(),
                             breaks = date_breaks("1 day"),
                             labels = date_format("%b %d %R", tz=time_zone),
                             limits = x_axis_range)
        
    } else { #Default is "hours"
        figure_plot =
            figure_plot +
            scale_x_datetime(name = element_blank(),
                             breaks = date_breaks("3 hour"),
                             labels = date_format("%b %d %R", tz=time_zone),
                             limits = x_axis_range)
    }
    
    figure_plot = 
        figure_plot +
        scale_y_continuous(name=y_axis_label) +
        scale_color_manual(values=display_color_mapping) +
        coord_cartesian(ylim = y_axis_range) +
        facet_grid(Display_Facet~., scales = "free_y") +
        theme(axis.text.x = element_text(angle = 50, hjust = 1),
              strip.background = element_blank())
    
    return(figure_plot)
}


#### Helper functions to format data

#Extract and format measurement periods for the given user. These will be used
#to set the x-axis limits for the plot.
filter_and_format.measurement_periods <- function(subjectID,
                                                  measurement_periods=NULL) {
    x_axis_ranges = NULL
    
    if(!is.null(measurement_periods)) {
        #Check to make sure there is data for the given subject
        if(subjectID %in% measurement_periods$SubjectID) {
            x_axis_ranges =
                measurement_periods %>%
                filter(SubjectID == subjectID) %>% 
                rename(start = Start.Time,
                       end = End.Time)
        }
    }
    return(x_axis_ranges)
}

#Extract and format measurement scales for the given set of measurements.
#These will be used to set the y-axis limits for the plot. This function
#allows you to specify a specific data source. If none is given, it will
#calculate the the scales from all given measurments, regardless of source.
filter_and_format.measurement_scales <- function(display_measurements,
                                                 measurement_scales=NULL,
                                                 source=NULL) {
    y_axis_ranges = NULL
    
    if(!is.null(measurement_scales)) {
        #Check to make sure there is data for any of the given measurements
        if(any(display_measurements %in% measurement_scales$Measurement)) {
            
            y_axis_ranges =
                measurement_scales %>%
                filter(Measurement %in% display_measurements)
            
            #Check to make sure there is data for the given source
            if(!is.null(source) & source %in% measurement_scales$Source) { 
                y_axis_ranges =
                    y_axis_ranges %>% 
                    filter(Source == source)
            }
            
            y_axis_ranges =
                y_axis_ranges %>%
                select(-Measurement, -Source) %>% 
                summarize(min_value = min(Min.scale, na.rm=TRUE),
                          max_value = max(Max.scale, na.rm=TRUE))
        }
    }
    return(y_axis_ranges)
}

#Extract and format sleep/wake times for the given user. These will be used
#to define shaded regions on the plot.
filter_and_format.sleep_wake_times <- function(subjectID,
                                               sleep_wake_times=NULL) {
    shaded_regions = NULL
    
    if(!is.null(sleep_wake_times)) {
        #Check to make sure there is data for the current subject
        if(subjectID %in% sleep_wake_times$SubjectID) {
            shaded_regions =
                sleep_wake_times %>% 
                filter(SubjectID == subjectID) %>% 
                select(SubjectID, Sleep.Period, DateTime, Sleep.Status) %>% 
                spread(Sleep.Status, DateTime) %>% 
                select(start, end)
        } 
    }
    return(shaded_regions)
}


#Extract and format treatment times for the given user. These will be used
#to define shaded regions on the plot.
filter_and_format.treatment_times <- function(subjectID,
                                              treatment_times=NULL) {
    vertical_line_locations = NULL
    
    if(!is.null(treatment_times)) {
        #Check to make sure there is data for the current subject
        if(subjectID %in% treatment_times$SubjectID) {
            vertical_line_locations =
                treatment_times %>%
                filter(SubjectID == subjectID)
        }
    }
    return(vertical_line_locations)
}


#### Wrapper plotting functions

#These wrappers prepare data for plotting the different data types. They call the
#helper functions and generic plotting functions defined above.

#Generate a single figure plotting data of the given type and source. This function
#will format all of the necessary data before pushing it on to the plotting function
#(plot_generic_time_series.multiple_days).
plot.generic_type_and_source.multiple_days <- function(subjectID,
                                                       input_data_table,
                                                       measurement_periods=NULL,
                                                       measurement_scales=NULL,
                                                       sleep_wake_times=NULL,
                                                       treatment_times=NULL,
                                                       plot_colors=c("#1b9e77"),
                                                       time_zone=default_timezone,
                                                       source=NULL,
                                                       Display_measurements = c(),
                                                       Display_facet_name = "Missing facet name",
                                                       Display_units = "Missing display units",
                                                       Group_by_Misc=FALSE) {
    
    #Filter input data structures for correct data type and source
    input_data = NULL
    input_data =
        input_data_table %>% 
        filter(SubjectID == subjectID,
               Measurement %in% Display_measurements) %>% 
        mutate(Display_Group = factor(Measurement,
                                      levels=Display_measurements),
               Display_Facet = factor(Display_facet_name)) %>% 
        select(-Measurement)
    
    #If the above filtering step yielded an empty table, do not progress to the
    #display functions below (they will fail).
    if(dim(input_data)[1] == 0) {
        warning(c("Empty table after filtering by Subject (", subjectID, ") and measurements (",
                  paste(Display_measurements, sep="", collapse=","), ")"))
        return(NULL)
    }
    
    #If the contents of the Misc column should be used for display grouping
    if(Group_by_Misc) {
        input_data =
            input_data %>% 
            mutate(Display_Group = factor(Misc))
    }
    
    #Map plot colors to display group
    Display_color_mapping = setNames(plot_colors, levels(input_data$Display_Group))
    
    #Filter data for given source (if specified)
    if(!is.null(source)) {
        input_data = 
            input_data %>% 
            filter(Source == source)
    }
    
    #Format display parameters
    x_axis_ranges = filter_and_format.measurement_periods(subjectID, measurement_periods)
    y_axis_ranges = filter_and_format.measurement_scales(Display_measurements, measurement_scales, source)
    shaded_regions = filter_and_format.sleep_wake_times(subjectID, sleep_wake_times)
    vertical_line_locations = filter_and_format.treatment_times(subjectID, treatment_times)
    
    #Plot the activity data for the current subject
    figure_plot = 
        plot_generic_time_series.multiple_days(input_data = input_data,
                                               y_axis_label = Display_units,
                                               display_color_mapping = Display_color_mapping,
                                               x_axis_range = c(x_axis_ranges$start,
                                                                x_axis_ranges$end),
                                               y_axis_range = c(y_axis_ranges$min_value,
                                                                y_axis_ranges$max_value),
                                               shaded_regions = shaded_regions,
                                               vertical_line_locations = vertical_line_locations$DateTime,
                                               time_zone=time_zone)
    return(figure_plot)
}


#Wrapper function to generate a single figure plotting vertical, lateral, and
#sagittal axes of motion derived from ZephyrBioPatch data. Note, for the
#plotting functions below I allow the user to display data from multiple
#bipatches as separate traces with distinct colors. Here I'm not implementing
#this option, since the three axes of motion are already being plotted together
#as separate traces. Adding data from multiple devices would just make the
#figures quite messy (given the current implementation of these functions). This
#is a limitation I should think about when it comes time to update/ redesign
#these functions.
plot.BioPatch_AxesOfMotion.multiple_days <- function(subjectID,
                                                     input_data_table,
                                                     measurement_periods=NULL,
                                                     measurement_scales=NULL,
                                                     sleep_wake_times=NULL,
                                                     treatment_times=NULL,
                                                     plot_colors=c("#a6761d", "#66a61e", "#533B0E"),
                                                     time_zone=default_timezone) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("Vertical", "Lateral", "Sagittal")
    Display_facet_name = "Axes of Motion"
    Display_units = "Average acceleration (g/min)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units)
}


#Wrapper function to generate a single figure plotting peak acceleration for the
#vertical, lateral, and sagittal axes of motion derived from ZephyrBioPatch
#data. Note, for the plotting functions below I allow the user to display data
#from multiple bipatches as separate traces with distinct colors. Here I'm not
#implementing this option, since the three axes of motion are already being
#plotted together as separate traces. Adding data from multiple devices would
#just make the figures quite messy (given the current implementation of these
#functions). This is a limitation I should think about when it comes time to
#update/ redesign these functions.
plot.BioPatch_AxesPeakAccel.multiple_days <- function(subjectID,
                                                      input_data_table,
                                                      measurement_periods=NULL,
                                                      measurement_scales=NULL,
                                                      sleep_wake_times=NULL,
                                                      treatment_times=NULL,
                                                      plot_colors=c("#a6761d", "#66a61e", "#533B0E"),
                                                      time_zone=default_timezone) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("VerticalPeak", "LateralPeak", "SagittalPeak")
    Display_facet_name = "Peak Accel - 3 Axes"
    Display_units = "Acceleration (g)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units)
}


#Wrapper function to generate a single figure plotting minimum acceleration for
#the vertical, lateral, and sagittal axes of motion derived from ZephyrBioPatch
#data. Note, for the plotting functions below I allow the user to display data
#from multiple bipatches as separate traces with distinct colors. Here I'm not
#implementing this option, since the three axes of motion are already being
#plotted together as separate traces. Adding data from multiple devices would
#just make the figures quite messy (given the current implementation of these
#functions). This is a limitation I should think about when it comes time to
#update/ redesign these functions.
plot.BioPatch_AxesMinAccel.multiple_days <- function(subjectID,
                                                     input_data_table,
                                                     measurement_periods=NULL,
                                                     measurement_scales=NULL,
                                                     sleep_wake_times=NULL,
                                                     treatment_times=NULL,
                                                     plot_colors=c("#a6761d", "#66a61e", "#533B0E"),
                                                     time_zone=default_timezone) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("VerticalMin", "LateralMin", "SagittalMin")
    Display_facet_name = "Min Accel - 3 Axes"
    Display_units = "Acceleration (g)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units)
}


#Wrapper function to generate a single figure plotting peak and minimum
#acceleration for the vertical, lateral, and sagittal axes of motion derived
#from ZephyrBioPatch data. Note, for the plotting functions below I allow the
#user to display data from multiple bipatches as separate traces with distinct
#colors. Here I'm not implementing this option, since the three axes of motion
#are already being plotted together as separate traces. Adding data from
#multiple devices would just make the figures quite messy (given the current
#implementation of these functions). This is a limitation I should think about
#when it comes time to update/ redesign these functions.
plot.BioPatch_AxesPeakMinAccel.multiple_days <- function(subjectID,
                                                         input_data_table,
                                                         measurement_periods=NULL,
                                                         measurement_scales=NULL,
                                                         sleep_wake_times=NULL,
                                                         treatment_times=NULL,
                                                         plot_colors=c("#a6761d", "#66a61e", "#533B0E",
                                                                       "#c9ac77", "#a3c978", "#97896e"),
                                                         time_zone=default_timezone) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("VerticalPeak", "LateralPeak", "SagittalPeak",
                             "VerticalMin", "LateralMin", "SagittalMin")
    Display_facet_name = "Peak/Min Accel - 3 Axes"
    Display_units = "Acceleration (g)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units)
}


#Wrapper function to generate a single figure plotting PeakAccel derived
#from ZephyrBioPatch data
plot.BioPatch_PeakAccel.multiple_days <- function(subjectID,
                                                  input_data_table,
                                                  measurement_periods=NULL,
                                                  measurement_scales=NULL,
                                                  sleep_wake_times=NULL,
                                                  treatment_times=NULL,
                                                  plot_colors=c("#1b9e77"),
                                                  time_zone=default_timezone,
                                                  #If multiple Biopatches were used to collect
                                                  #data from a single subject, plot these with
                                                  #separate colors.
                                                  plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("PeakAccel")
    Display_facet_name = "Peak Acceleration"
    Display_units = "Acceleration (g)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}

#Wrapper function to generate a single figure plotting activity derived
#from actigraphy data generated by the BioPatch device.
plot.Activity_from_BioPatch.multiple_days <- function(subjectID,
                                                      input_data_table,
                                                      measurement_periods=NULL,
                                                      measurement_scales=NULL,
                                                      sleep_wake_times=NULL,
                                                      treatment_times=NULL,
                                                      plot_colors=c("#1b9e77"),
                                                      time_zone=default_timezone) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("Activity")
    Display_facet_name = "Activity"
    Display_units = "Vector Magnitude Units (g)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=TRUE)
}


#Wrapper function to generate a single figure plotting vector magnitude derived
#from ZephyrBioPatch data
plot.BioPatch_VectorMagnitude.multiple_days <- function(subjectID,
                                                        input_data_table,
                                                        measurement_periods=NULL,
                                                        measurement_scales=NULL,
                                                        sleep_wake_times=NULL,
                                                        treatment_times=NULL,
                                                        plot_colors=c("#1b9e77"),
                                                        time_zone=default_timezone,
                                                        #If multiple Biopatches were used to collect
                                                        #data from a single subject, plot these with
                                                        #separate colors.
                                                        plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("VectorMagnitude")
    Display_facet_name = "Vector Magnitude"
    Display_units = "Average acceleration (g/min)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting breathing waveform
#derived from ZephyrBioPatch data
plot.BioPatch_BreathingWaveform.multiple_days <- function(subjectID,
                                                          input_data_table,
                                                          measurement_periods=NULL,
                                                          measurement_scales=NULL,
                                                          sleep_wake_times=NULL,
                                                          treatment_times=NULL,
                                                          plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                          time_zone=default_timezone,
                                                          #If multiple Biopatches were used to collect
                                                          #data from a single subject, plot these with
                                                          #separate colors.
                                                          plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("BreathingWaveform")
    Display_facet_name = "Breathing Waveform"
    Display_units = "Bits"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting BRAmplitude
#derived from ZephyrBioPatch data
plot.BioPatch_BRAmplitude.multiple_days <- function(subjectID,
                                                    input_data_table,
                                                    measurement_periods=NULL,
                                                    measurement_scales=NULL,
                                                    sleep_wake_times=NULL,
                                                    treatment_times=NULL,
                                                    plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                    time_zone=default_timezone,
                                                    #If multiple Biopatches were used to collect
                                                    #data from a single subject, plot these with
                                                    #separate colors.
                                                    plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("BRAmplitude")
    Display_facet_name = "Breathing amplitude"
    Display_units = "Bits"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting BRNoise
#derived from ZephyrBioPatch data
plot.BioPatch_BRNoise.multiple_days <- function(subjectID,
                                                input_data_table,
                                                measurement_periods=NULL,
                                                measurement_scales=NULL,
                                                sleep_wake_times=NULL,
                                                treatment_times=NULL,
                                                plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                time_zone=default_timezone,
                                                #If multiple Biopatches were used to collect
                                                #data from a single subject, plot these with
                                                #separate colors.
                                                plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("BRNoise")
    Display_facet_name = "Breathing noise"
    Display_units = "Bits"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting BRConfidence
#derived from ZephyrBioPatch data
plot.BioPatch_BRConfidence.multiple_days <- function(subjectID,
                                                     input_data_table,
                                                     measurement_periods=NULL,
                                                     measurement_scales=NULL,
                                                     sleep_wake_times=NULL,
                                                     treatment_times=NULL,
                                                     plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                     time_zone=default_timezone,
                                                     #If multiple Biopatches were used to collect
                                                     #data from a single subject, plot these with
                                                     #separate colors.
                                                     plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("BRConfidence")
    Display_facet_name = "Breathing confidence"
    Display_units = "Percent confidence"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting ECGAmplitude
#derived from ZephyrBioPatch data
plot.BioPatch_ECGAmplitude.multiple_days <- function(subjectID,
                                                     input_data_table,
                                                     measurement_periods=NULL,
                                                     measurement_scales=NULL,
                                                     sleep_wake_times=NULL,
                                                     treatment_times=NULL,
                                                     plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                     time_zone=default_timezone,
                                                     #If multiple Biopatches were used to collect
                                                     #data from a single subject, plot these with
                                                     #separate colors.
                                                     plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("ECGAmplitude")
    Display_facet_name = "ECG amplitude"
    Display_units = "Volts"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting ECGNoise
#derived from ZephyrBioPatch data
plot.BioPatch_ECGNoise.multiple_days <- function(subjectID,
                                                 input_data_table,
                                                 measurement_periods=NULL,
                                                 measurement_scales=NULL,
                                                 sleep_wake_times=NULL,
                                                 treatment_times=NULL,
                                                 plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                 time_zone=default_timezone,
                                                 #If multiple Biopatches were used to collect
                                                 #data from a single subject, plot these with
                                                 #separate colors.
                                                 plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("ECGNoise")
    Display_facet_name = "ECG noise"
    Display_units = "Volts"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting HRConfidence
#derived from ZephyrBioPatch data
plot.BioPatch_HRConfidence.multiple_days <- function(subjectID,
                                                     input_data_table,
                                                     measurement_periods=NULL,
                                                     measurement_scales=NULL,
                                                     sleep_wake_times=NULL,
                                                     treatment_times=NULL,
                                                     plot_colors=c("#1b9e77", "#a6761d", "#66a61e", "#533B0E"),
                                                     time_zone=default_timezone,
                                                     #If multiple Biopatches were used to collect
                                                     #data from a single subject, plot these with
                                                     #separate colors.
                                                     plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("HRConfidence")
    Display_facet_name = "Heart rate confidence"
    Display_units = "Percent confidence"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting HRV derived from
#ZephyrBioPatch data. Note, HRV data are plotted over a much shorter time
#period (a few hours) that most of the other data types. Since the generic
#plotting functions aren't currently configure to allow this, I'm modifing
#the x-axis of graph returned by the generic plotting function to scale
#appropriately.
plot.BioPatch_HRV <- function(subjectID,
                              input_data_table,
                              measurement_periods=NULL,
                              measurement_scales=NULL,
                              sleep_wake_times=NULL,
                              treatment_times=NULL,
                              plot_colors=c("#1b9e77"),
                              time_zone=default_timezone,
                              #If multiple Biopatches were used to collect
                              #data from a single subject, plot these with
                              #separate colors.
                              plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("HRV")
    Display_facet_name = "Heart Rate Variability"
    Display_units = "R-R Interval (ms)"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately) #+
    # scale_x_datetime(name = "Time (HH:MM)",
    #                  breaks = scales::date_breaks("10 min"),
    #                  labels = scales::date_format("%R", tz=default_timezone))
}


#Wrapper function to generate a single figure plotting core body temperature
#derived from ZephyrBioPatch data.
plot.BioPatch_CoreTemp.multiple_days <- function(subjectID,
                                                 input_data_table,
                                                 measurement_periods=NULL,
                                                 measurement_scales=NULL,
                                                 sleep_wake_times=NULL,
                                                 treatment_times=NULL,
                                                 plot_colors=c("#7570b3", "#8b104e"),
                                                 time_zone=default_timezone,
                                                 #If multiple Biopatches were used to collect
                                                 #data from a single subject, plot these with
                                                 #separate colors.
                                                 plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("CoreTemp")
    Display_facet_name = "Core Temperature"
    Display_units = expression(paste0(output_directory, "/", subjectID, "/Core temp (", degree, "C)"))
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting skin temperature
#derived from ZephyrBioPatch data.
plot.BioPatch_SkinTemp.multiple_days <- function(subjectID,
                                                 input_data_table,
                                                 measurement_periods=NULL,
                                                 measurement_scales=NULL,
                                                 sleep_wake_times=NULL,
                                                 treatment_times=NULL,
                                                 plot_colors=c("#7570b3", "#8b104e"),
                                                 time_zone=default_timezone,
                                                 #If multiple Biopatches were used to collect
                                                 #data from a single subject, plot these with
                                                 #separate colors.
                                                 plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("SkinTemp")
    Display_facet_name = "Skin Temperature"
    Display_units = expression(paste0(output_directory, "/", subjectID, "/Skin temp (", degree, "C)"))
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting heart rate
#derived from ZephyrBioPatch data.
plot.BioPatch_HR.multiple_days <- function(subjectID,
                                           input_data_table,
                                           measurement_periods=NULL,
                                           measurement_scales=NULL,
                                           sleep_wake_times=NULL,
                                           treatment_times=NULL,
                                           plot_colors=c("#7570b3", "#8b104e"),
                                           time_zone=default_timezone,
                                           #If multiple Biopatches were used to collect
                                           #data from a single subject, plot these with
                                           #separate colors.
                                           plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("HR")
    Display_facet_name = "Heart rate"
    Display_units = "Beats per minute"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting breathing rate
#derived from ZephyrBioPatch data.
plot.BioPatch_BR.multiple_days <- function(subjectID,
                                           input_data_table,
                                           measurement_periods=NULL,
                                           measurement_scales=NULL,
                                           sleep_wake_times=NULL,
                                           treatment_times=NULL,
                                           plot_colors=c("#7570b3", "#8b104e"),
                                           time_zone=default_timezone,
                                           #If multiple Biopatches were used to collect
                                           #data from a single subject, plot these with
                                           #separate colors.
                                           plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("BR")
    Display_facet_name = "Breathing rate"
    Display_units = "Breaths per minute"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


#Wrapper function to generate a single figure plotting posture
#derived from ZephyrBioPatch data.
plot.BioPatch_Posture.multiple_days <- function(subjectID,
                                                input_data_table,
                                                measurement_periods=NULL,
                                                measurement_scales=NULL,
                                                sleep_wake_times=NULL,
                                                treatment_times=NULL,
                                                plot_colors=c("#7570b3", "#8b104e"),
                                                time_zone=default_timezone,
                                                #If multiple Biopatches were used to collect
                                                #data from a single subject, plot these with
                                                #separate colors.
                                                plot_multiple_devices_separately=FALSE) {
    #Prepare graph/display parameters
    Display_source = "ZephyrBioPatch"
    Display_measurements = c("Posture")
    Display_facet_name = "Posture"
    Display_units = "Degrees from vertical"
    
    #Generate plot
    plot.generic_type_and_source.multiple_days(subjectID,
                                               input_data_table,
                                               measurement_periods,
                                               measurement_scales,
                                               sleep_wake_times,
                                               treatment_times,
                                               plot_colors,
                                               time_zone,
                                               Display_source,
                                               Display_measurements,
                                               Display_facet_name,
                                               Display_units,
                                               Group_by_Misc=plot_multiple_devices_separately)
}


### Utility functions

filter.BioPatch_invalid_values <- function(input_data_table) {
    
    filtered.input_data_table =
        input_data_table %>% 
        mutate(Invalid_Values =
                   case_when(
                       Source == "ZephyrBioPatch" & Measurement == "HRV" & Value == 65535 ~ TRUE,
                       Source == "ZephyrBioPatch" & Measurement == "CoreTemp" & Value == 6553.5 ~ TRUE,
                       Source == "ZephyrBioPatch" & Measurement == "BRNoise" & Value == 65535 ~ TRUE,
                       Source == "ZephyrBioPatch" & Measurement == "BreathingWaveform" & Value == 0 ~ TRUE,
                       Source == "ZephyrBioPatch" & Measurement == "BreathingWaveform" & Value == 16777216 ~ TRUE,
                       TRUE ~ FALSE))
    
    #Output counts for invalid values filtered out by function.
    filtered.input_data_table %>% 
        filter(Invalid_Values,
               Source == "ZephyrBioPatch") %>% 
        count(SubjectID, Source, Measurement, Value) %>% 
        rename(Invalid_Value = Value,
               Count = n) %>%
        print()
    
    #Return filtered input table
    filtered.input_data_table %>% 
        filter(!Invalid_Values) %>% 
        select(-Invalid_Values) %>% 
        return()
}


#' Aggregate data over given time interval
#'
#' @param input_data A tbl() or data.frame containing time and signal columns to
#'   scale.
#' @param aggregate_interval Unit of time over which to aggregate. This argument
#'   should be one of "secs", "mins", "hours", "days", (default: "hours").
#' @param aggregate_function Function to use when aggregating data over the
#'   given time interval. Currently accepts "mean" or "sum" (default: "mean").
#'   Either choice uses the na.rm=TRUE option to remove NA values during the
#'   calculation.
#'
#' @return
#' @export
#'
#' @examples
aggregate_data_by_time <- function(input_data,
                                   aggregate_interval="hours",
                                   aggregate_function="mean") {
    
    if(!(aggregate_interval %in% c("secs", "mins", "hours", "days"))) {
        stop("Unrecognized value \"",aggregate_interval,"\" entered for aggregate_interval.\n",
             "       Must be one of \"secs\", \"mins\", \"hours\", \"days\".")
    }
    if(!(aggregate_function %in% c("mean", "sum"))) {
        stop("Unrecognized value \"",aggregate_function,"\" entered for aggregate_function.\n",
             "       Must be one of \"mean\", \"sum\".")
    }
    
    #Store original order of column names
    original_colnames = colnames(input_data)
    
    input_data %>%
        mutate(DateTime =
                   case_when(
                       aggregate_interval == "secs" ~ ymd_hms(format(DateTime, "%Y:%m:%d %H:%M:%S"), tz = tz(DateTime)),
                       aggregate_interval == "mins" ~ ymd_hm(format(DateTime, "%Y:%m:%d %H:%M"), tz = tz(DateTime)),
                       aggregate_interval == "hours" ~ ymd_h(format(DateTime, "%Y:%m:%d %H"), tz = tz(DateTime)),
                       aggregate_interval == "days" ~ ymd(format(DateTime, "%Y:%m:%d"), tz = tz(DateTime))
                   )) %>% 
        group_by(across(-Value)) %>% 
        # Use across since it's a little easier to specify an arbitrary function
        # to apply to the Value column. There are probably better ways to do this.
        # Need to specify the .names, otherwise the result of summarize will be
        # "Value_1", since the function is provided in a list.
        summarize(across(Value, list(!!aggregate_function), na.rm=TRUE, .names="{col}")) %>% 
        ungroup() %>% 
        relocate(all_of(original_colnames))
}


### Function for Cosinor analyses

library(rlang)
library(broom)

#Requires broom, purr, dplyr, tidyr, readr

#This version of the function extracts more of the parameters (including some fit
#parameters) than the original function. It does not calculate the derived parameters,
#and instead relies on a helper function to do that.

#' Cosinor analysis
#'
#' The following algorithm is adapted from
#' https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3991883/ .
#'
#'
#' @param input_data A tbl() or data.frame containing time and signal columns
#'   for cosinor analysis.
#' @param time Bare name of the column with the time information. The time
#'   column should be a type compatible with the difftime() function.
#' @param signal Bare name of the column with the signal data. The signal column
#'   should be of type dbl.
#' @param ... (Optional) Bare column names to group by.
#' @param period Length of period for cosinor analysis in hours (Default: 24).
#' @param confidence_level The level of confidence used when determining the
#'   confidence interval (Default: 0.95).
#'
#' @return
#' @export
#'
#' @examples
fit_cosine_to_data <- function(input_data,
                               time,
                               signal,
                               ...,
                               period=24,
                               confidence_level=0.95) {
    
    #"Quote" column names so they are ready for use below
    time_col <- enquo(time)
    signal_col <- enquo(signal)
    group_by_cols <- quos(...)
    
    #Perform regression based on the given grouping variables.
    regression_results =
        input_data %>% 
        #Renaming the signal column simplifies the code below. I could unquote
        #all occurrences of this column using UQ(), like I do with the time
        #column. However, this doesn't work in the lm() call below.
        rename(Signal_Column = UQ(signal_col)) %>% 
        #Calculate the start times for each signal.
        group_by(UQS(group_by_cols)) %>% 
        mutate(Group.Start = min(UQ(time_col))) %>% 
        ungroup() %>% 
        #Calculate the Cosinor.Time as hours since the start time. The
        #Corrected.Cosinor.Time converts the hours since the start time to match
        #the 24-hour clock time. This makes it easier to calculate the phase
        #below.
        mutate(Cosinor.Time = as.double(difftime(UQ(time_col), Group.Start, units=c("hours"))),
               Corrected.Cosinor.Time = Cosinor.Time + hour(Group.Start) +
                   minute(Group.Start)/60 + second(Group.Start)/3600) %>% 
        select(UQS(group_by_cols), Corrected.Cosinor.Time, Signal_Column) %>% 
        unique() %>% 
        group_by(UQS(group_by_cols)) %>% 
        mutate(x = cos(2*pi*Corrected.Cosinor.Time/period),
               z = sin(2*pi*Corrected.Cosinor.Time/period)) %>% 
        tidyr::nest() %>% 
        #Perform fit and extract results at the coefficient level and fit level.
        mutate(fit = purrr::map(data, ~ lm(Signal_Column ~ x + z, data=.x)),
               #Return the 95% confidence intervals for each coefficient.
               tidied = purrr::map(fit, broom::tidy, conf.int=TRUE, conf.level=confidence_level),
               glanced = purrr::map(fit, broom::glance))
    
    #Merge the coefficient data with the fit summary stats. Note, I had to use
    #rbind instead of bind_rows, because this was causing some weird conflicts
    #with the UQS quosures that I couldn't debug.
    rbind(
        regression_results %>%
            select(-data, -fit, -glanced) %>% 
            tidyr::unnest(tidied) %>%
            #Now rename coefficients to match what names we use to derive cosinor parameters
            mutate(term = recode(term,
                                 `(Intercept)` = "MESOR",
                                 `x` = "beta",
                                 `z` = "gamma")) %>%
            select(-statistic) %>%
            gather(stat, value, -c(UQS(group_by_cols)), -term) %>%
            unite(lm.results, term, stat, sep="_"),
        regression_results %>%
            select(-data, -fit, -tidied) %>%
            tidyr::unnest(glanced) %>%
            gather(term, value, -c(UQS(group_by_cols))) %>%
            mutate(lm.results = paste0("fit_", term)) %>%
            select(UQS(group_by_cols), lm.results, value)
    ) %>%
        arrange(UQS(group_by_cols), lm.results)
}


#*#*#*#



# Process data in given directory -----
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

# Read and process command-line arguments for this script:
args = commandArgs(TRUE)
zephyr_directory = args[1]
output_directory = args[2]
exclusion_table_filename = args[3]

# Set the default timezone used when reading in all timestamps. This default
# parameter is required by the functions defined above.
default_timezone = "America/New_York"

# Extract subject ID from directory
subjectID = gsub(".*/([^/]+)(/)?","\\1", zephyr_directory)

# Get list of all files
zephyr_filenames = list.files(path=zephyr_directory, include.dirs = TRUE, full.names = TRUE,
                              pattern = ".*_(Accel\\.formatted_for_R|Breathing|Summary)\\.csv")

# Load exclusion table. Note, this code assumes there are 0 or 1 entries in the
# exclusion table for each subject/file root combination. This script does not
# currently support multiple exclusion periods within the same file.
exclusion_table =
    read_tsv(exclusion_table_filename,
             col_types = 
                 cols(
                     SubjectID = col_character(),
                     Start = col_datetime(format = ""),
                     Stop = col_datetime(format = ""),
                     File_stem_to_drop = col_character()
                 )) %>% 
    mutate(Start = force_tz(Start, tzone = default_timezone),
           Stop = force_tz(Stop, tzone = default_timezone))

# Read each file and collect the results
merged_zephyr_results = tibble()

# Process each of the various zephyr data files
for(file in zephyr_filenames) {
    
    # Given the current filename, identify the corresponding exclusion regions
    # (if any). These will be used to filter the input from the file.
    exclusion_range =
        exclusion_table %>%
        # Need rowwise, since we want a separate comparison for each entry in
        # the File_stem_to_drop column to the current filename.
        rowwise() %>%
        filter(grepl(File_stem_to_drop, file),
               SubjectID == subjectID) %>%
        # Ungroup to remove the rowwise grouping.
        ungroup() %>% 
        select(Start, Stop)
    # If there are no entries for the current subject/filename combination, set
    # the start and stop columns to NA. This is so the bind_cols commands work
    # below, even if there are no exclusion ranges.
    if(dim(exclusion_range)[1] == 0) {
        # Make sure both NA columns are of type 'dttm'
        exclusion_range = tibble(Start = as.POSIXct(NA), Stop = as.POSIXct(NA))
    }
    
    # Determine data source and run appropriate reader function. Add columns for
    # Start and Stop of exclusion period corresponding to each file for the
    # given subject. If there is no exclusion period, then these columns will
    # contain NA values.
    if(grepl("Accel", file)) {
        merged_zephyr_results =
            merged_zephyr_results %>% 
            bind_rows(read.BioPatch_accelerometer_data(file, subjectID) %>% 
                          bind_cols(exclusion_range))
    } else if(grepl("Breathing", file)) {
        merged_zephyr_results =
            merged_zephyr_results %>% 
            bind_rows(read.BioPatch_breathing_data(file, subjectID) %>% 
                          aggregate_data_by_time(aggregate_interval = "mins") %>% 
                          bind_cols(exclusion_range))
    } else if(grepl("Summary", file)) {
        merged_zephyr_results =
            merged_zephyr_results %>% 
            bind_rows(read.BioPatch_data.everything(file, subjectID) %>% 
                          bind_cols(exclusion_range))
    }
}

# Filter out measurements matching times from the exclusion table.
merged_zephyr_results =
    merged_zephyr_results %>% 
    filter(is.na(Start) | !(DateTime >= Start & DateTime <= Stop)) %>% 
    select(-Start, -Stop)

# Convert several columns to factors
merged_zephyr_results =
    merged_zephyr_results %>% 
    mutate(Measurement = factor(Measurement),
           Source = factor(Source),
           SubjectID = factor(SubjectID))

# Filter invalid values
merged_zephyr_results =
    merged_zephyr_results %>% 
    filter.BioPatch_invalid_values()

# Save the gathered, processed dataset
merged_zephyr_results %>% 
    # Remove subject ID and Source columns since this info is already contained
    # in the filename, and this cuts down on the memory footprint. Remove Misc
    # column because it's not used in this dataset also saves on the memory
    # footprint. These exclusions drop file sizes by ~60%.
    select(-SubjectID, -Source, -Misc) %>% 
    mutate(DateTime = as.character(DateTime)) %>% 
    write_tsv(paste0(output_directory, "/Aggregated_data.ZephyrBioPatch.",
                     subjectID, ".txt"))

#*#*#*#




# Plot ZephyrBioPatch data streams ----
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

# Save these plots together in pdf files.

pdf(paste0(output_directory, "/Plots.ZephyrBioPatch.", subjectID, ".axes_of_motion.pdf"),
    width = 7, height = 4)
plot.BioPatch_AxesOfMotion.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_AxesPeakAccel.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_AxesMinAccel.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_AxesPeakMinAccel.multiple_days(subjectID, merged_zephyr_results)
dev.off()

pdf(paste0(output_directory, "/Plots.ZephyrBioPatch.", subjectID, ".aggregated_activity.pdf"),
    width = 7, height = 4)
plot.BioPatch_VectorMagnitude.multiple_days(subjectID, merged_zephyr_results)
plot.Activity_from_BioPatch.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_PeakAccel.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_Posture.multiple_days(subjectID, merged_zephyr_results)
dev.off()

pdf(paste0(output_directory, "/Plots.ZephyrBioPatch.", subjectID, ".breathing_metrics.pdf"),
    width = 7, height = 4)
plot.BioPatch_BreathingWaveform.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_BR.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_BRAmplitude.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_BRNoise.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_BRConfidence.multiple_days(subjectID, merged_zephyr_results)
dev.off()

pdf(paste0(output_directory, "/Plots.ZephyrBioPatch.", subjectID, ".heart_metrics.pdf"),
    width = 7, height = 4)
plot.BioPatch_HR.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_HRConfidence.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_ECGAmplitude.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_ECGNoise.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_HRV(subjectID, merged_zephyr_results)
dev.off()

pdf(paste0(output_directory, "/Plots.ZephyrBioPatch.", subjectID, ".body_temperature.pdf"),
    width = 7, height = 4)
plot.BioPatch_CoreTemp.multiple_days(subjectID, merged_zephyr_results)
plot.BioPatch_SkinTemp.multiple_days(subjectID, merged_zephyr_results)
dev.off()

#*#*#*#




# Perform Cosinor analysis of data streams ----
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

merged_zephyr.cosinor_results =
    merged_zephyr_results %>%
    fit_cosine_to_data(time = DateTime,
                       signal = Value,
                       SubjectID, Source, Measurement, Misc)
    
# Save the cosinor results
merged_zephyr.cosinor_results %>%
    write_tsv(paste0(output_directory, "/Cosinor_results.ZephyrBioPatch.", subjectID, ".txt"))

#*#*#*#